pe-de-pizza/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

pe-de-pizza/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pe-de-pizza/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def user_params
        params.require(:user).permit(:name, :lastname, :email, :phone, :password, :password_confirmation)
    end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

pe-de-pizza/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

pe-de-pizza/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    user = User.find_by(email: params[:session][:email.downcase])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      @user = User.new
      flash.now[:notice] = 'Combinação de e-mail e senha inválida.'
      respond_to do |format|
      format.html {
        flash.now[:notice] = 'Combinação de e-mail e senha inválida.'
        render :new, notice: 'AWDWADA'
      }
      end
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end

end

pe-de-pizza/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

pe-de-pizza/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.email = @user.email.downcase

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    user_info = user_params
    user_info.delete(:is_admin) if !current_user.is_admin?
    respond_to do |format|
      if @user.update(user_info)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :phone, :password, :password_confirmation, :is_admin)
    end
end

pe-de-pizza/app/helpers/application_helper.rb
module ApplicationHelper
end

pe-de-pizza/app/helpers/sessions_helper.rb
module SessionsHelper
    
def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

pe-de-pizza/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

pe-de-pizza/app/helpers/users_helper.rb
module UsersHelper
end

pe-de-pizza/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pizzaria Pé de Pizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="container">
      <a href="/">
      <div class="logo">
        <%= image_tag("logo.svg") %>
         <h1>Pé de Pizza</h1>
      </div>
      </a>

      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/#cardapio">Cardápio</a></li>
          <li><a href="/#quem-somos">Quem somos</a></li>
          <li><a href="/#contato">Contato</a></li>
          <li><% if logged_in? %>
                <%= link_to 'Sair', logout_path, method: :delete %>
              <% else %>
                <%= link_to 'Entrar', login_path %>
              <% end %></li>
        </ul>
      </nav>
    </div>
  </header>


    <%= yield %>


  <footer>
    <p>Feito com muito carinho e vontade de pizza pela {IN} Junior</p>
    <p>Webmaster & webdesigner: Niasi</p>
  </footer>  
  </body>
</html>

pe-de-pizza/app/views/static_pages/home.html.erb
<section id="home">


<div id="pizza-carousel" class="carousel slide" data-ride="carousel">
    <!-- nav dots -->
    <ol class="carousel-indicators">
        <li data-target="#pizza-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#pizza-carousel" data-slide-to="1"></li>
        <li data-target="#pizza-carousel" data-slide-to="2"></li>
    </ol>
    <!-- wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <%= image_tag("carousel-1.png", class: "cover") %>
        </div>
        <div class="item">
            <%= image_tag("carousel-2.png", class: "cover") %>
        </div>
        <div class="item">
            <%= image_tag("carousel-3.png", class: "cover") %>
        </div>
    </div>
    <!-- next and prev arrows -->
    <a class="left carousel-control" href="#pizza-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#pizza-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>



</section>

pe-de-pizza/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "nome" %>
  </div>

  <div class="field">
    <%= form.text_field :lastname, placeholder: "sobrenome" %>
  </div>

  <div class="field">
    <%= form.text_field :email, placeholder: "e-mail" %>
  </div>

  <div class="field">
    <%= form.text_field :phone, placeholder: "telefone" %>
  </div>

  <div class="field">
    <%= form.password_field :password, placeholder: "senha" %>
  </div>
  
	<div class="field">
    <%= form.password_field :password_confirmation, placeholder: "confirmar senha" %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>
<% end %>

pe-de-pizza/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

pe-de-pizza/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Is admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %> <%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

pe-de-pizza/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

pe-de-pizza/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.name %> <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>